export const countryData = [
  { countryName: "Afghanistan", countryCode: "AF", telCode: "+93" },
  { countryName: "Albania", countryCode: "AL", telCode: "+355" },
  { countryName: "Algeria", countryCode: "DZ", telCode: "+213" },
  { countryName: "Andorra", countryCode: "AD", telCode: "+376" },
  { countryName: "Angola", countryCode: "AO", telCode: "+244" },
  { countryName: "Antigua and Barbuda", countryCode: "AG", telCode: "+1-268" },
  { countryName: "Argentina", countryCode: "AR", telCode: "+54" },
  { countryName: "Armenia", countryCode: "AM", telCode: "+374" },
  { countryName: "Australia", countryCode: "AU", telCode: "+61" },
  { countryName: "Austria", countryCode: "AT", telCode: "+43" },
  { countryName: "Azerbaijan", countryCode: "AZ", telCode: "+994" },
  { countryName: "Bahamas", countryCode: "BS", telCode: "+1-242" },
  { countryName: "Bahrain", countryCode: "BH", telCode: "+973" },
  { countryName: "Bangladesh", countryCode: "BD", telCode: "+880" },
  { countryName: "Barbados", countryCode: "BB", telCode: "+1-246" },
  { countryName: "Belarus", countryCode: "BY", telCode: "+375" },
  { countryName: "Belgium", countryCode: "BE", telCode: "+32" },
  { countryName: "Belize", countryCode: "BZ", telCode: "+501" },
  { countryName: "Benin", countryCode: "BJ", telCode: "+229" },
  { countryName: "Bhutan", countryCode: "BT", telCode: "+975" },
  { countryName: "Bolivia", countryCode: "BO", telCode: "+591" },
  { countryName: "Bosnia and Herzegovina", countryCode: "BA", telCode: "+387" },
  { countryName: "Botswana", countryCode: "BW", telCode: "+267" },
  { countryName: "Brazil", countryCode: "BR", telCode: "+55" },
  { countryName: "Brunei", countryCode: "BN", telCode: "+673" },
  { countryName: "Bulgaria", countryCode: "BG", telCode: "+359" },
  { countryName: "Burkina Faso", countryCode: "BF", telCode: "+226" },
  { countryName: "Burundi", countryCode: "BI", telCode: "+257" },
  { countryName: "Cabo Verde", countryCode: "CV", telCode: "+238" },
  { countryName: "Cambodia", countryCode: "KH", telCode: "+855" },
  { countryName: "Cameroon", countryCode: "CM", telCode: "+237" },
  { countryName: "Canada", countryCode: "CA", telCode: "+1" },
  {
    countryName: "Central African Republic",
    countryCode: "CF",
    telCode: "+236"
  },
  { countryName: "Chad", countryCode: "TD", telCode: "+235" },
  { countryName: "Chile", countryCode: "CL", telCode: "+56" },
  { countryName: "China", countryCode: "CN", telCode: "+86" },
  { countryName: "Colombia", countryCode: "CO", telCode: "+57" },
  { countryName: "Comoros", countryCode: "KM", telCode: "+269" },
  {
    countryName: "Congo (Congo-Brazzaville)",
    countryCode: "CG",
    telCode: "+242"
  },
  { countryName: "Congo (Congo-Kinshasa)", countryCode: "CD", telCode: "+243" },
  { countryName: "Costa Rica", countryCode: "CR", telCode: "+506" },
  { countryName: "Croatia", countryCode: "HR", telCode: "+385" },
  { countryName: "Cuba", countryCode: "CU", telCode: "+53" },
  { countryName: "Cyprus", countryCode: "CY", telCode: "+357" },
  { countryName: "Czech Republic", countryCode: "CZ", telCode: "+420" },
  { countryName: "Denmark", countryCode: "DK", telCode: "+45" },
  { countryName: "Djibouti", countryCode: "DJ", telCode: "+253" },
  { countryName: "Dominica", countryCode: "DM", telCode: "+1-767" },
  { countryName: "Dominican Republic", countryCode: "DO", telCode: "+1-809" },
  {
    countryName: "East Timor (Timor-Leste)",
    countryCode: "TL",
    telCode: "+670"
  },
  { countryName: "Ecuador", countryCode: "EC", telCode: "+593" },
  { countryName: "Egypt", countryCode: "EG", telCode: "+20" },
  { countryName: "El Salvador", countryCode: "SV", telCode: "+503" },
  { countryName: "Equatorial Guinea", countryCode: "GQ", telCode: "+240" },
  { countryName: "Eritrea", countryCode: "ER", telCode: "+291" },
  { countryName: "Estonia", countryCode: "EE", telCode: "+372" },
  { countryName: "Eswatini", countryCode: "SZ", telCode: "+268" },
  { countryName: "Ethiopia", countryCode: "ET", telCode: "+251" },
  { countryName: "Fiji", countryCode: "FJ", telCode: "+679" },
  { countryName: "Finland", countryCode: "FI", telCode: "+358" },
  { countryName: "France", countryCode: "FR", telCode: "+33" },
  { countryName: "Gabon", countryCode: "GA", telCode: "+241" },
  { countryName: "Gambia", countryCode: "GM", telCode: "+220" },
  { countryName: "Georgia", countryCode: "GE", telCode: "+995" },
  { countryName: "Germany", countryCode: "DE", telCode: "+49" },
  { countryName: "Ghana", countryCode: "GH", telCode: "+233" },
  { countryName: "Greece", countryCode: "GR", telCode: "+30" },
  { countryName: "Grenada", countryCode: "GD", telCode: "+1-473" },
  { countryName: "Guatemala", countryCode: "GT", telCode: "+502" },
  { countryName: "Guinea", countryCode: "GN", telCode: "+224" },
  { countryName: "Guinea-Bissau", countryCode: "GW", telCode: "+245" },
  { countryName: "Guyana", countryCode: "GY", telCode: "+592" },
  { countryName: "Haiti", countryCode: "HT", telCode: "+509" },
  { countryName: "Honduras", countryCode: "HN", telCode: "+504" },
  { countryName: "Hungary", countryCode: "HU", telCode: "+36" },
  { countryName: "Iceland", countryCode: "IS", telCode: "+354" },
  { countryName: "India", countryCode: "IN", telCode: "+91" },
  { countryName: "Indonesia", countryCode: "ID", telCode: "+62" },
  { countryName: "Iran", countryCode: "IR", telCode: "+98" },
  { countryName: "Iraq", countryCode: "IQ", telCode: "+964" },
  { countryName: "Ireland", countryCode: "IE", telCode: "+353" },
  { countryName: "Israel", countryCode: "IL", telCode: "+972" },
  { countryName: "Italy", countryCode: "IT", telCode: "+39" },
  { countryName: "Jamaica", countryCode: "JM", telCode: "+1-876" },
  { countryName: "Japan", countryCode: "JP", telCode: "+81" },
  { countryName: "Jordan", countryCode: "JO", telCode: "+962" },
  { countryName: "Kazakhstan", countryCode: "KZ", telCode: "+7" },
  { countryName: "Kenya", countryCode: "KE", telCode: "+254" },
  { countryName: "Kiribati", countryCode: "KI", telCode: "+686" },
  { countryName: "Korea (North)", countryCode: "KP", telCode: "+850" },
  { countryName: "Korea (South)", countryCode: "KR", telCode: "+82" },
  { countryName: "Kuwait", countryCode: "KW", telCode: "+965" },
  { countryName: "Kyrgyzstan", countryCode: "KG", telCode: "+996" },
  { countryName: "Laos", countryCode: "LA", telCode: "+856" },
  { countryName: "Latvia", countryCode: "LV", telCode: "+371" },
  { countryName: "Lebanon", countryCode: "LB", telCode: "+961" },
  { countryName: "Lesotho", countryCode: "LS", telCode: "+266" },
  { countryName: "Liberia", countryCode: "LR", telCode: "+231" },
  { countryName: "Libya", countryCode: "LY", telCode: "+218" },
  { countryName: "Liechtenstein", countryCode: "LI", telCode: "+423" },
  { countryName: "Lithuania", countryCode: "LT", telCode: "+370" },
  { countryName: "Luxembourg", countryCode: "LU", telCode: "+352" },
  { countryName: "Madagascar", countryCode: "MG", telCode: "+261" },
  { countryName: "Malawi", countryCode: "MW", telCode: "+265" },
  { countryName: "Malaysia", countryCode: "MY", telCode: "+60" },
  { countryName: "Maldives", countryCode: "MV", telCode: "+960" },
  { countryName: "Mali", countryCode: "ML", telCode: "+223" },
  { countryName: "Malta", countryCode: "MT", telCode: "+356" },
  { countryName: "Marshall Islands", countryCode: "MH", telCode: "+692" },
  { countryName: "Mauritania", countryCode: "MR", telCode: "+222" },
  { countryName: "Mauritius", countryCode: "MU", telCode: "+230" },
  { countryName: "Mexico", countryCode: "MX", telCode: "+52" },
  { countryName: "Micronesia", countryCode: "FM", telCode: "+691" },
  { countryName: "Moldova", countryCode: "MD", telCode: "+373" },
  { countryName: "Monaco", countryCode: "MC", telCode: "+377" },
  { countryName: "Mongolia", countryCode: "MN", telCode: "+976" },
  { countryName: "Montenegro", countryCode: "ME", telCode: "+382" },
  { countryName: "Morocco", countryCode: "MA", telCode: "+212" },
  { countryName: "Mozambique", countryCode: "MZ", telCode: "+258" },
  { countryName: "Myanmar", countryCode: "MM", telCode: "+95" },
  { countryName: "Namibia", countryCode: "NA", telCode: "+264" },
  { countryName: "Nauru", countryCode: "NR", telCode: "+674" },
  { countryName: "Nepal", countryCode: "NP", telCode: "+977" },
  { countryName: "Netherlands", countryCode: "NL", telCode: "+31" },
  { countryName: "New Zealand", countryCode: "NZ", telCode: "+64" },
  { countryName: "Nicaragua", countryCode: "NI", telCode: "+505" },
  { countryName: "Niger", countryCode: "NE", telCode: "+227" },
  { countryName: "Nigeria", countryCode: "NG", telCode: "+234" },
  { countryName: "North Macedonia", countryCode: "MK", telCode: "+389" },
  { countryName: "Norway", countryCode: "NO", telCode: "+47" },
  { countryName: "Oman", countryCode: "OM", telCode: "+968" },
  { countryName: "Pakistan", countryCode: "PK", telCode: "+92" },
  { countryName: "Palau", countryCode: "PW", telCode: "+680" },
  { countryName: "Panama", countryCode: "PA", telCode: "+507" },
  { countryName: "Papua New Guinea", countryCode: "PG", telCode: "+675" },
  { countryName: "Paraguay", countryCode: "PY", telCode: "+595" },
  { countryName: "Peru", countryCode: "PE", telCode: "+51" },
  { countryName: "Philippines", countryCode: "PH", telCode: "+63" },
  { countryName: "Poland", countryCode: "PL", telCode: "+48" },
  { countryName: "Portugal", countryCode: "PT", telCode: "+351" },
  { countryName: "Qatar", countryCode: "QA", telCode: "+974" },
  { countryName: "Romania", countryCode: "RO", telCode: "+40" },
  { countryName: "Russia", countryCode: "RU", telCode: "+7" },
  { countryName: "Rwanda", countryCode: "RW", telCode: "+250" },
  {
    countryName: "Saint Kitts and Nevis",
    countryCode: "KN",
    telCode: "+1-869"
  },
  { countryName: "Saint Lucia", countryCode: "LC", telCode: "+1-758" },
  {
    countryName: "Saint Vincent and the Grenadines",
    countryCode: "VC",
    telCode: "+1-784"
  },
  { countryName: "Samoa", countryCode: "WS", telCode: "+685" },
  { countryName: "San Marino", countryCode: "SM", telCode: "+378" },
  { countryName: "Sao Tome and Principe", countryCode: "ST", telCode: "+239" },
  { countryName: "Saudi Arabia", countryCode: "SA", telCode: "+966" },
  { countryName: "Senegal", countryCode: "SN", telCode: "+221" },
  { countryName: "Serbia", countryCode: "RS", telCode: "+381" },
  { countryName: "Seychelles", countryCode: "SC", telCode: "+248" },
  { countryName: "Sierra Leone", countryCode: "SL", telCode: "+232" },
  { countryName: "Singapore", countryCode: "SG", telCode: "+65" },
  { countryName: "Slovakia", countryCode: "SK", telCode: "+421" },
  { countryName: "Slovenia", countryCode: "SI", telCode: "+386" },
  { countryName: "Solomon Islands", countryCode: "SB", telCode: "+677" },
  { countryName: "Somalia", countryCode: "SO", telCode: "+252" },
  { countryName: "South Africa", countryCode: "ZA", telCode: "+27" },
  { countryName: "South Sudan", countryCode: "SS", telCode: "+211" },
  { countryName: "Spain", countryCode: "ES", telCode: "+34" },
  { countryName: "Sri Lanka", countryCode: "LK", telCode: "+94" },
  { countryName: "Sudan", countryCode: "SD", telCode: "+249" },
  { countryName: "Suriname", countryCode: "SR", telCode: "+597" },
  { countryName: "Sweden", countryCode: "SE", telCode: "+46" },
  { countryName: "Switzerland", countryCode: "CH", telCode: "+41" },
  { countryName: "Syria", countryCode: "SY", telCode: "+963" },
  { countryName: "Taiwan", countryCode: "TW", telCode: "+886" },
  { countryName: "Tajikistan", countryCode: "TJ", telCode: "+992" },
  { countryName: "Tanzania", countryCode: "TZ", telCode: "+255" },
  { countryName: "Thailand", countryCode: "TH", telCode: "+66" },
  { countryName: "Togo", countryCode: "TG", telCode: "+228" },
  { countryName: "Tonga", countryCode: "TO", telCode: "+676" },
  { countryName: "Trinidad and Tobago", countryCode: "TT", telCode: "+1-868" },
  { countryName: "Tunisia", countryCode: "TN", telCode: "+216" },
  { countryName: "Turkey", countryCode: "TR", telCode: "+90" },
  { countryName: "Turkmenistan", countryCode: "TM", telCode: "+993" },
  { countryName: "Tuvalu", countryCode: "TV", telCode: "+688" },
  { countryName: "Uganda", countryCode: "UG", telCode: "+256" },
  { countryName: "Ukraine", countryCode: "UA", telCode: "+380" },
  { countryName: "United Arab Emirates", countryCode: "AE", telCode: "+971" },
  { countryName: "United Kingdom", countryCode: "GB", telCode: "+44" },
  { countryName: "United States", countryCode: "US", telCode: "+1" },
  { countryName: "Uruguay", countryCode: "UY", telCode: "+598" },
  { countryName: "Uzbekistan", countryCode: "UZ", telCode: "+998" },
  { countryName: "Vanuatu", countryCode: "VU", telCode: "+678" },
  { countryName: "Vatican City", countryCode: "VA", telCode: "+39" },
  { countryName: "Venezuela", countryCode: "VE", telCode: "+58" },
  { countryName: "Vietnam", countryCode: "VN", telCode: "+84" },
  { countryName: "Yemen", countryCode: "YE", telCode: "+967" },
  { countryName: "Zambia", countryCode: "ZM", telCode: "+260" },
  { countryName: "Zimbabwe", countryCode: "ZW", telCode: "+263" }
]
